sudo: required
language: generic
env:
  global:
    - AZ_REPO=$(lsb_release -cs)
    #tag docker images
    - DOCKER_WEB_IMAGE=$DOCKER_USERNAME/fask-web:$TRAVIS_COMMIT
    - DOCKER_NGINX_IMAGE=$DOCKER_USERNAME/fask-nginx:$TRAVIS_COMMIT 
service:
  - docker
before_install:
# Installation steps for docker-compose
- sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker-compose version
# Downloading Azure CLI and install script
# Get packages needed for the install process
- sudo apt-get update
- sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
# Download and install the Microsoft signing key
- curl -sL https://packages.microsoft.com/keys/microsoft.asc | 
      gpg --dearmor | 
      sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
# Add the Azure CLI software repository
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | 
        sudo tee /etc/apt/sources.list.d/azure-cli.list
# Update repository information and install the azure-cli package
- sudo apt-get update
- sudo apt-get install azure-cli
# Install Kubectl command
- sudo az aks install-cli     
deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master 