sudo: required
language: generic
env:
  global:
    - AZ_REPO=$(lsb_release -cs)
service:
  - docker
before_install:
# Installation steps for docker-compose
- sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker-compose version
#
install:
- docker-compose up -d
- docker ps
- docker-compose down 