sudo: required
language: generic
env:
  global:
    - AZ_REPO=$(lsb_release -cs)
    #tag docker images
    - DOCKER_WEB_IMAGE=$DOCKER_USERNAME/fask-web:$TRAVIS_COMMIT
    - DOCKER_NGINX_IMAGE=$DOCKER_USERNAME/fask-nginx:$TRAVIS_COMMIT 
service:
  - docker
   
deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master 