version: '3'

services:

  redis:
    image: redis
    networks: 
      - fask_network   

  web:
    build:
      context: ./web/
    # Rename image based on docker_account/image_name  
    image: jehaddocker82/fask-web:v1  
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks: 
      - fask_network   
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    restart: always
    build: ./nginx/
    # Rename image based on docker_account/image_name  
    image: jehaddocker82/fask-nginx:v1  
    ports:
      - "8080:80"
    volumes:
      - "fask_volume:/usr/share/nginx/html"  
    networks: 
      - fask_network  

volumes:
   fask_volume:

networks: 
    fask_network:   