version: '3'

services:

  redis:
    image: redis
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT_NUMBER=6379
    networks: 
      - flask_network   

  web:
    build:
      context: ./web/
    # Rename image based on docker_account/image_name  
    image: jehaddocker/fask-web  
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks: 
      - flask_network   

  nginx:
    restart: always
    build: ./nginx/
    # Rename image based on docker_account/image_name  
    image: jehaddocker/fask-nginx  
    ports:
      - "8080:80"
    links:
      - web
    volumes:
      - "flask_volume:/usr/share/nginx/html"  
    networks: 
      - flask_network  

volumes:
   flask_volume:

networks: 
    flask_network:   