apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: abujoj-com-tls
spec:
  secretName: abujoj-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: abujoj.com
  dnsNames:
     - abujoj.com
     - www.abujoj.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - abujoj.com
          - www.abujoj.com