# Create a StorageClass object pointing to the existing Storage Account
# Remember: that the Storage account must be in the same Resource Group where the AKS cluster is deployed
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fask-storageclass
  namespace: fask-namespace
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: faskstorage
  location: “Central US”

---
# keep it at the top to avoid persistentvolumeclaim "volume" not found
# creating a persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fasknginxpv
  namespace: fask-namespace
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: fask-storageclass
  persistentVolumeReclaimPolicy: Retain  
  azureFile:
    secretName: fask-secret
    # Share Name (must already exist in the storage account) 
    shareName: fask-fileshare
    readOnly: false

---
# deploying a claim, so pods can mount the volume via the claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fask-nginx-pvc
  namespace: fask-namespace
spec:
  accessModes:
     - ReadWriteMany
  resources:
      requests:
          storage: 10Gi
  volumeName: fasknginxpv    
  storageClassName: fask-storageclass

---
# To build nginx pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fask-nginx-deployment
  namespace: fask-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      restartPolicy: Always            
      containers:
        - name: fask-nginx-container
          image: jehaddocker82/fask-nginx:v2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: fask-mountv
              mountPath: /etc/nginx/
      volumes:
          - name: fask-mountv
            persistentVolumeClaim:
                claimName: fask-nginx-pvc              

---
# To build nginx cluster service
apiVersion: v1
kind: Service
metadata:
  name: fask-nginx-service
  namespace: fask-namespace  
spec:
  type: ClusterIP
  selector:
    component: nginx
  ports:
    - port: 80
      targetPort: 80