# creating a new volume type PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fask-nginx-volume
  namespace: fask-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi