apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fask-ingress-resource
  namespace: fask-namespace
  annotations:
    # to create ingress controller basded on nginx 
    kubernetes.io/ingress.class: nginx
    # disable SSL auto redirection
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # rewrite rule remove appendix such as /app and change it to / 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      # backend to default home page
      - backend:
          serviceName: fask-nginx-service
          servicePort: 80
        path: /(.*)
      # backend to another service if you called /api (it's just an example)  
      - backend:
          serviceName: fask-web-service
          servicePort: 8000
        path: /api(/|$)(.*)
